#!/bin/bash
pushd . >/dev/null
PROBLEM_DIR=$(dirname $(realpath "$0"))
CONTEST_DIR=$(dirname $PROBLEM_DIR)
cd $CONTEST_DIR
bazel build //PDIR:solve && rm -f $PROBLEM_DIR/solve && cp $CONTEST_DIR/bazel-bin/PDIR/solve $PROBLEM_DIR/
popd >/dev/null
