#!/bin/bash
set -e
END_DIR="G"
if [ $# -ge 1 ]; then
  END_DIR="$1"
fi

if [[ ! "$END_DIR" =~ ^[A-Z]$ ]]; then
  echo "invalid argument"
  exit 1
fi

pushd .>/dev/null
CONTEST_DIR="$(dirname "$(dirname "$(realpath "$0")")")/contest"
mkdir -p "$CONTEST_DIR"
cd "$CONTEST_DIR"
rm -rf [A-Z] &>/dev/null

cp -r ../template/third_party ./
cp ../template/MODULE.bazel ./
for DIR in {A..Z}; do
  if [[ "$DIR" > "$END_DIR" ]]; then
    break
  fi
  cp -rT ../template/problem "$DIR"
  sed "s/PDIR/$DIR/g" ../template/problem/compile >$DIR/compile
done

bazel clean
bazel fetch //...
popd >/dev/null
